/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Jellyfin',
      items: [{ type: 'autogenerated', dirName: 'jellyfin' }],
      collapsed: false, // Prevents this category from collapsing
    },
    {
      type: 'category',
      label: 'Apps',
      items: [{ type: 'autogenerated', dirName: 'apps' }],
      collapsed: false,
    },
  ],
};

export default sidebars;
